---
- name: idempotent_command check idempotent file
  ansible.builtin.command: cat "{{ idempotent_command__path }}"
  register: __idempotent_command__check_result
  changed_when: false
  failed_when: false

- name: idempotent_command debug
  ansible.builtin.debug:
    var: __idempotent_command__check_result

- name: idempotent_command write content
  ansible.builtin.shell: |-
    echo -n {{ idempotent_command__content | quote }} 
    > {{ idempotent_command__path | quote }}
  when: __idempotent_command__check_result.stdout != idempotent_command__content
