ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_port: 22
ansible_user: worker
ansible_ssh_pass: "{{ valut__ansible_ssh_pass }}"
ansible_sudo_pass: "{{ valut__ansible_sudo_pass }}"
